# Generated by Django 5.0.6 on 2024-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='Room_foodincluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='Room_servicesincluded',
            field=models.BooleanField(default=False),
        ),
    ]
