# Generated by Django 5.0.6 on 2024-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_houses_room_foodincluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='Room_capacity',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='Room_location',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
