# Generated by Django 5.0.6 on 2024-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_remove_houses_room_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='Room_contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_img',
            field=models.ImageField(null=True, upload_to='rooms'),
        ),
    ]
