# Generated by Django 5.0.6 on 2024-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_houses_room_contact_number_alter_houses_room_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='Room_contact_number',
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_amentities',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_capacity',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_img',
            field=models.ImageField(upload_to='rooms'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_maximumstay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_minimumstay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_priceperday',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='Room_size',
            field=models.IntegerField(),
        ),
    ]
